<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Attribute extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Attribute_model');
    }

    /*
     * Listing of attribute
     */

    function index() {
        $data['attribute'] = $this->Attribute_model->get_all_attribute();

        $data['_view'] = 'attribute/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new attribute
     */

    function add() {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'name' => $this->input->post('name'),
            );

            $attribute_id = $this->Attribute_model->add_attribute($params);
            redirect('../analyse_home');
        } else {
            $data['_view'] = 'attribute/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a attribute
     */

    function edit($idattribute) {
        // check if the attribute exists before trying to edit it
        $data['attribute'] = $this->Attribute_model->get_attribute($idattribute);

        if (isset($data['attribute']['idattribute'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'name' => $this->input->post('name'),
                );

                $this->Attribute_model->update_attribute($idattribute, $params);
                redirect('attribute/index');
            } else {
                $data['_view'] = 'attribute/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The attribute you are trying to edit does not exist.');
    }

    /*
     * Deleting attribute
     */

    function remove($idattribute) {
        $attribute = $this->Attribute_model->get_attribute($idattribute);

        // check if the attribute exists before trying to delete it
        if (isset($attribute['idattribute'])) {
            $this->Attribute_model->delete_attribute($idattribute);
            redirect('attribute/index');
        } else
            show_error('The attribute you are trying to delete does not exist.');
    }

    function filter() {
        if (isset($_POST) && count($_POST) > 0) {

            $name = $this->input->post('name');
            $player = $this->input->post('player');
            $attribList = "";
            if ($name != "") {
                $attribList = $this->Attribute_model->get_filtered_attributes_by_name($name);
            } else if ($player != "") {
                $attribList = $this->Attribute_model->get_filtered_attributes_by_player($player);
            } else if ($name == "" && $player == "") {
                $attribList = $this->Attribute_model->get_filtered_attributes_by_name($name);
            }

            echo json_encode($attribList);
        } else {
            echo 'else';
        }
    }

}
