<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Location extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Location_model');
    } 

    /*
     * Listing of location
     */
    function index()
    {
        $data['location'] = $this->Location_model->get_all_location();
        
        $data['_view'] = 'location/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new location
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $location_id = $this->Location_model->add_location($params);
            redirect('location/index');
        }
        else
        {            
            $data['_view'] = 'location/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a location
     */
    function edit($idocation)
    {   
        // check if the location exists before trying to edit it
        $data['location'] = $this->Location_model->get_location($idocation);
        
        if(isset($data['location']['idocation']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Location_model->update_location($idocation,$params);            
                redirect('location/index');
            }
            else
            {
                $data['_view'] = 'location/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The location you are trying to edit does not exist.');
    } 

    /*
     * Deleting location
     */
    function remove($idocation)
    {
        $location = $this->Location_model->get_location($idocation);

        // check if the location exists before trying to delete it
        if(isset($location['idocation']))
        {
            $this->Location_model->delete_location($idocation);
            redirect('location/index');
        }
        else
            show_error('The location you are trying to delete does not exist.');
    }
    
}
