<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Match_has_team extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Match_has_team_model');
    } 

    /*
     * Listing of match_has_team
     */
    function index()
    {
        $data['match_has_team'] = $this->Match_has_team_model->get_all_match_has_team();
        
        $data['_view'] = 'match_has_team/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new match_has_team
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idmatch' => $this->input->post('idmatch'),
				'idteam' => $this->input->post('idteam'),
            );
            
            $match_has_team_id = $this->Match_has_team_model->add_match_has_team($params);
            redirect('match_has_team/index');
        }
        else
        {            
            $data['_view'] = 'match_has_team/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a match_has_team
     */
    function edit($idmatch_has_team)
    {   
        // check if the match_has_team exists before trying to edit it
        $data['match_has_team'] = $this->Match_has_team_model->get_match_has_team($idmatch_has_team);
        
        if(isset($data['match_has_team']['idmatch_has_team']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idmatch' => $this->input->post('idmatch'),
					'idteam' => $this->input->post('idteam'),
                );

                $this->Match_has_team_model->update_match_has_team($idmatch_has_team,$params);            
                redirect('match_has_team/index');
            }
            else
            {
                $data['_view'] = 'match_has_team/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The match_has_team you are trying to edit does not exist.');
    } 

    /*
     * Deleting match_has_team
     */
    function remove($idmatch_has_team)
    {
        $match_has_team = $this->Match_has_team_model->get_match_has_team($idmatch_has_team);

        // check if the match_has_team exists before trying to delete it
        if(isset($match_has_team['idmatch_has_team']))
        {
            $this->Match_has_team_model->delete_match_has_team($idmatch_has_team);
            redirect('match_has_team/index');
        }
        else
            show_error('The match_has_team you are trying to delete does not exist.');
    }
    
}
