<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Match_idmatch extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Match_idmatch_model');
    }

    /*
     * Listing of match_idmatch
     */

    function index() {
        $data['match_idmatch'] = $this->Match_idmatch_model->get_all_match_idmatch();

        $data['_view'] = 'match_idmatch/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new match_idmatch
     */

    function add() {
        if (isset($_POST) && count($_POST) > 0) {
            $idMatch = $this->input->post('idmatch');
            $params = array(
                'idtype' => $this->input->post('idtype'),
                'runs' => $this->input->post('runs'),
                'idballer' => $this->input->post('idballer'),
                'idbatsman' => $this->input->post('idbatsman'),
                'idthirdplayer' => $this->input->post('idthirdplayer'),
            );

            $match_idmatch_id = $this->Match_idmatch_model->add_match_idmatch($idMatch, $params);
            $data = $this->Match_idmatch_model->each_ball_calculation($idMatch);
            echo json_encode($data);
        } else {
            $data['_view'] = 'match_idmatch/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a match_idmatch
     */

    function edit($ballno) {
        // check if the match_idmatch exists before trying to edit it
        $data['match_idmatch'] = $this->Match_idmatch_model->get_match_idmatch($ballno);

        if (isset($data['match_idmatch']['ballno'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'idtype' => $this->input->post('idtype'),
                    'runs' => $this->input->post('runs'),
                    'idballer' => $this->input->post('idballer'),
                    'idbatsman' => $this->input->post('idbatsman'),
                    'idthirdplayer' => $this->input->post('idthirdplayer'),
                );

                $this->Match_idmatch_model->update_match_idmatch($ballno, $params);
                redirect('match_idmatch/index');
            } else {
                $data['_view'] = 'match_idmatch/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The match_idmatch you are trying to edit does not exist.');
    }

    /*
     * Deleting match_idmatch
     */

    function remove($ballno) {
        $match_idmatch = $this->Match_idmatch_model->get_match_idmatch($ballno);

        // check if the match_idmatch exists before trying to delete it
        if (isset($match_idmatch['ballno'])) {
            $this->Match_idmatch_model->delete_match_idmatch($ballno);
            redirect('match_idmatch/index');
        } else
            show_error('The match_idmatch you are trying to delete does not exist.');
    }

    function create_match() {
        if (isset($_POST) && count($_POST) > 0) {
            $idMatch = $this->input->post('matchid');
            $this->load->model('Team_model');
            $this->load->model('Match_model');
            $this->load->model('Player_model');
            $match = $this->Match_model->get_match($idMatch);
            //
            $data['data']['batsman_01'] = $this->input->post('bat1'); //
            $data['data']['batsman_02'] = $this->input->post('bat2'); //
            $tossteam = $match['toss'];
            $elected = $match['elected'];
            //
            if ($match['status'] == '1') {
                //echo $this->input->post('toss')." - ".$this->input->post('elected');
                //
                $params = array(
                    'status' => '2',
                    'toss' => $tossteam,
                    'elected' => $elected,
                );

                $this->Match_model->update_match($idMatch, $params);
                //
                $this->Match_idmatch_model->create_match_idmatch($idMatch);
            } else {
                $currentBattingPair = $this->Match_model->getCurrentBatsmanPair($idMatch);
                $data['data']['batsman_01'] = $currentBattingPair['strike'];
                $data['data']['batsman_02'] = $currentBattingPair['nonstrike'];
            }
            //
            $match = $this->Match_model->get_match($idMatch);
            //

            $team_1 = $this->Match_model->get_match($idMatch)['team1'];
            $team_2 = $this->Match_model->get_match($idMatch)['team2'];
            $ballNumber = $this->Match_idmatch_model->get_last_ball_number($idMatch)['ballno'];
            $inning = $this->Match_model->getInning($idMatch);
            $ballingBatting = $this->Match_model->getCurrentBattingBallingTeam($idMatch);
            $batteam = $ballingBatting['batting_team'];
            $ballteam = $ballingBatting['ballting_team'];
            //
            $data['data']['idmatch'] = $idMatch;
            $data['data']['batteam'] = $batteam;
            $data['data']['batteam_name'] = $this->Team_model->get_team($batteam)['name'] . ($batteam == $tossteam ? " - <span style='font-size: 16px'>Won the toss and elected to " . ($elected == "1" ? "Bat</span>" : "Bowl</span>") : "");
            $data['data']['ballteam'] = $ballteam;
            $data['data']['ballteam_name'] = $this->Team_model->get_team($ballteam)['name'] . ($ballteam == $tossteam ? " - <span style='font-size: 16px'>Won the toss and elected to " . ($elected == "1" ? "Bat</span>" : "Bowl</span>") : "");
            $data['data']['ballno'] = $ballNumber == "" ? "0" : $ballNumber;
            $data['data']['team_1'] = $team_1;
            $data['data']['team_2'] = $team_2;
            $data['data']['team_1_players'] = $this->Player_model->get_players_by_match_team($idMatch, $team_1);
            $data['data']['team_2_players'] = $this->Player_model->get_players_by_match_team($idMatch, $team_2);
            //
            $this->load->view('broadcast/broadcasting', $data);
        }
    }

    function get_match_details() {
//        $idMatch = $this->input->post('idmatch');
//        $data = $this->Match_idmatch_model->each_ball_calculation($idMatch);
//        echo json_encode($data);
        echo 'ok';
    }

}
