<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Match_team_has_player extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Match_team_has_player_model');
    } 

    /*
     * Listing of match_team_has_players
     */
    function index()
    {
        $data['match_team_has_players'] = $this->Match_team_has_player_model->get_all_match_team_has_players();
        
        $data['_view'] = 'match_team_has_player/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new match_team_has_player
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idmatch' => $this->input->post('idmatch'),
				'idteam' => $this->input->post('idteam'),
				'idplayer' => $this->input->post('idplayer'),
				'position' => $this->input->post('position'),
            );
            
            $match_team_has_player_id = $this->Match_team_has_player_model->add_match_team_has_player($params);
            redirect('match_team_has_player/index');
        }
        else
        {            
            $data['_view'] = 'match_team_has_player/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a match_team_has_player
     */
    function edit($idmatch_team_has_players)
    {   
        // check if the match_team_has_player exists before trying to edit it
        $data['match_team_has_player'] = $this->Match_team_has_player_model->get_match_team_has_player($idmatch_team_has_players);
        
        if(isset($data['match_team_has_player']['idmatch_team_has_players']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idmatch' => $this->input->post('idmatch'),
					'idteam' => $this->input->post('idteam'),
					'idplayer' => $this->input->post('idplayer'),
					'position' => $this->input->post('position'),
                );

                $this->Match_team_has_player_model->update_match_team_has_player($idmatch_team_has_players,$params);            
                redirect('match_team_has_player/index');
            }
            else
            {
                $data['_view'] = 'match_team_has_player/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The match_team_has_player you are trying to edit does not exist.');
    } 

    /*
     * Deleting match_team_has_player
     */
    function remove($idmatch_team_has_players)
    {
        $match_team_has_player = $this->Match_team_has_player_model->get_match_team_has_player($idmatch_team_has_players);

        // check if the match_team_has_player exists before trying to delete it
        if(isset($match_team_has_player['idmatch_team_has_players']))
        {
            $this->Match_team_has_player_model->delete_match_team_has_player($idmatch_team_has_players);
            redirect('match_team_has_player/index');
        }
        else
            show_error('The match_team_has_player you are trying to delete does not exist.');
    }
    
}
