<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Player_type extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Player_type_model');
    } 

    /*
     * Listing of player_type
     */
    function index()
    {
        $data['player_type'] = $this->Player_type_model->get_all_player_type();
        
        $data['_view'] = 'player_type/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new player_type
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'type' => $this->input->post('type'),
            );
            
            $player_type_id = $this->Player_type_model->add_player_type($params);
            redirect('player_type/index');
        }
        else
        {            
            $data['_view'] = 'player_type/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a player_type
     */
    function edit($idtype)
    {   
        // check if the player_type exists before trying to edit it
        $data['player_type'] = $this->Player_type_model->get_player_type($idtype);
        
        if(isset($data['player_type']['idtype']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'type' => $this->input->post('type'),
                );

                $this->Player_type_model->update_player_type($idtype,$params);            
                redirect('player_type/index');
            }
            else
            {
                $data['_view'] = 'player_type/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The player_type you are trying to edit does not exist.');
    } 

    /*
     * Deleting player_type
     */
    function remove($idtype)
    {
        $player_type = $this->Player_type_model->get_player_type($idtype);

        // check if the player_type exists before trying to delete it
        if(isset($player_type['idtype']))
        {
            $this->Player_type_model->delete_player_type($idtype);
            redirect('player_type/index');
        }
        else
            show_error('The player_type you are trying to delete does not exist.');
    }
    
}
