<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Player_has_attribute extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Player_has_attribute_model');
    } 

    /*
     * Listing of player_has_attribute
     */
    function index()
    {
        $data['player_has_attribute'] = $this->Player_has_attribute_model->get_all_player_has_attribute();
        
        $data['_view'] = 'player_has_attribute/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new player_has_attribute
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idplayer' => $this->input->post('idplayer'),
				'idmatch' => $this->input->post('idmatch'),
				'idattribute' => $this->input->post('idattribute'),
				'level' => $this->input->post('level'),
            );
            
            $player_has_attribute_id = $this->Player_has_attribute_model->add_player_has_attribute($params);
            redirect('../analyse_map');
        }
        else
        {            
            $data['_view'] = 'player_has_attribute/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a player_has_attribute
     */
    function edit($idplayer_has_attribute)
    {   
        // check if the player_has_attribute exists before trying to edit it
        $data['player_has_attribute'] = $this->Player_has_attribute_model->get_player_has_attribute($idplayer_has_attribute);
        
        if(isset($data['player_has_attribute']['idplayer_has_attribute']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idplayer' => $this->input->post('idplayer'),
					'idmatch' => $this->input->post('idmatch'),
					'level' => $this->input->post('level'),
                );

                $this->Player_has_attribute_model->update_player_has_attribute($idplayer_has_attribute,$params);            
                redirect('player_has_attribute/index');
            }
            else
            {
                $data['_view'] = 'player_has_attribute/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The player_has_attribute you are trying to edit does not exist.');
    } 

    /*
     * Deleting player_has_attribute
     */
    function remove($idplayer_has_attribute)
    {
        $player_has_attribute = $this->Player_has_attribute_model->get_player_has_attribute($idplayer_has_attribute);

        // check if the player_has_attribute exists before trying to delete it
        if(isset($player_has_attribute['idplayer_has_attribute']))
        {
            $this->Player_has_attribute_model->delete_player_has_attribute($idplayer_has_attribute);
            redirect('player_has_attribute/index');
        }
        else
            show_error('The player_has_attribute you are trying to delete does not exist.');
    }
    
}
