<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Player_team_history extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Player_team_history_model');
    } 

    /*
     * Listing of player_team_history
     */
    function index()
    {
        $data['player_team_history'] = $this->Player_team_history_model->get_all_player_team_history();
        
        $data['_view'] = 'player_team_history/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new player_team_history
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idplayer' => $this->input->post('idplayer'),
				'from_date' => $this->input->post('from_date'),
				'to_date' => $this->input->post('to_date'),
				'idteam' => $this->input->post('idteam'),
            );
            
            $player_team_history_id = $this->Player_team_history_model->add_player_team_history($params);
            redirect('player_team_history/index');
        }
        else
        {            
            $data['_view'] = 'player_team_history/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a player_team_history
     */
    function edit($idplayer_team_history)
    {   
        // check if the player_team_history exists before trying to edit it
        $data['player_team_history'] = $this->Player_team_history_model->get_player_team_history($idplayer_team_history);
        
        if(isset($data['player_team_history']['idplayer_team_history']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idplayer' => $this->input->post('idplayer'),
					'from_date' => $this->input->post('from_date'),
					'to_date' => $this->input->post('to_date'),
					'idteam' => $this->input->post('idteam'),
                );

                $this->Player_team_history_model->update_player_team_history($idplayer_team_history,$params);            
                redirect('player_team_history/index');
            }
            else
            {
                $data['_view'] = 'player_team_history/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The player_team_history you are trying to edit does not exist.');
    } 

    /*
     * Deleting player_team_history
     */
    function remove($idplayer_team_history)
    {
        $player_team_history = $this->Player_team_history_model->get_player_team_history($idplayer_team_history);

        // check if the player_team_history exists before trying to delete it
        if(isset($player_team_history['idplayer_team_history']))
        {
            $this->Player_team_history_model->delete_player_team_history($idplayer_team_history);
            redirect('player_team_history/index');
        }
        else
            show_error('The player_team_history you are trying to delete does not exist.');
    }
    
}
