<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Player extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Player_model');
    }

    /*
     * Listing of player
     */

    function index() {
        $data['player'] = $this->Player_model->get_all_player();

        $data['_view'] = 'player/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new player
     */

    function add() {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'current_team' => $this->input->post('team'),
                'dob' => $this->input->post('dob'),
                'name' => $this->input->post('name'),
                'contact' => $this->input->post('contact'),
                'image' => 'default.jpg',
            );

            $player_id = $this->Player_model->add_player($params);
            redirect('../data_home#add');
        } else {
            $data['_view'] = 'player/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a player
     */

    function edit($idplayer) {
        // check if the player exists before trying to edit it
        $data['player'] = $this->Player_model->get_player($idplayer);

        if (isset($data['player']['idplayer'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'current_team' => $this->input->post('current_team'),
                    'dob' => $this->input->post('dob'),
                    'f_name' => $this->input->post('f_name'),
                    'l_name' => $this->input->post('l_name'),
                    'contact' => $this->input->post('contact'),
                    'image' => $this->input->post('image'),
                );

                $this->Player_model->update_player($idplayer, $params);
                redirect('player/index');
            } else {
                $data['_view'] = 'player/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The player you are trying to edit does not exist.');
    }

    /*
     * Deleting player
     */

    function remove($idplayer) {
        $player = $this->Player_model->get_player($idplayer);

        // check if the player exists before trying to delete it
        if (isset($player['idplayer'])) {
            $this->Player_model->delete_player($idplayer);
            redirect('player/index');
        } else
            show_error('The player you are trying to delete does not exist.');
    }

    function filter() {
        if (isset($_POST) && count($_POST) > 0) {

            $name = $this->input->post('name');
            $age = $this->input->post('age');
            $team = $this->input->post('team');

            $playerList = $this->Player_model->get_filtered_players($name, $age, $team);

            echo json_encode($playerList);
        } else {
            echo 'else';
        }
    }

    function get_players_by_match_team() {
        if (isset($_POST) && count($_POST) > 0) {
            $idTeam = $this->input->post('idteam');
            $idMatch = $this->input->post('idmatch');
            $playerList = $this->Player_model->get_players_by_match_team($idMatch, $idTeam);
            echo json_encode($playerList);
        } else {
            echo 'else';
        }
    }

}
