<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Attribute_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get attribute by idattribute
     */

    function get_attribute($idattribute) {
        return $this->db->get_where('attribute', array('idattribute' => $idattribute))->row_array();
    }

    /*
     * Get all attribute
     */

    function get_all_attribute() {
        $this->db->order_by('idattribute', 'desc');
        return $this->db->get('attribute')->result_array();
    }

    /*
     * function to add new attribute
     */

    function add_attribute($params) {
        $this->db->insert('attribute', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update attribute
     */

    function update_attribute($idattribute, $params) {
        $this->db->where('idattribute', $idattribute);
        return $this->db->update('attribute', $params);
    }

    /*
     * function to delete attribute
     */

    function delete_attribute($idattribute) {
        return $this->db->delete('attribute', array('idattribute' => $idattribute));
    }

    function get_filtered_attributes_by_name($name) {
        $query = "SELECT  * FROM attribute WHERE name LIKE '" . $name . "%'";
        $query = $this->db->query($query);
        return $query->result_array();
    }

    function get_filtered_attributes_by_player($player) {
        $query = "SELECT * FROM attribute WHERE idattribute IN (SELECT idattribute FROM player_has_attribute WHERE idplayer IN (SELECT idplayer FROM player WHERE name LIKE '" . $player . "%'))";
        $query = $this->db->query($query);
        return $query->result_array();
    }

}
