<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Match_has_team_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get match_has_team by idmatch_has_team
     */
    function get_match_has_team($idmatch_has_team)
    {
        return $this->db->get_where('match_has_team',array('idmatch_has_team'=>$idmatch_has_team))->row_array();
    }
        
    /*
     * Get all match_has_team
     */
    function get_all_match_has_team()
    {
        $this->db->order_by('idmatch_has_team', 'desc');
        return $this->db->get('match_has_team')->result_array();
    }
        
    /*
     * function to add new match_has_team
     */
    function add_match_has_team($params)
    {
        $this->db->insert('match_has_team',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update match_has_team
     */
    function update_match_has_team($idmatch_has_team,$params)
    {
        $this->db->where('idmatch_has_team',$idmatch_has_team);
        return $this->db->update('match_has_team',$params);
    }
    
    /*
     * function to delete match_has_team
     */
    function delete_match_has_team($idmatch_has_team)
    {
        return $this->db->delete('match_has_team',array('idmatch_has_team'=>$idmatch_has_team));
    }
}
