<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Match_team_has_player_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get match_team_has_player by idmatch_team_has_players
     */
    function get_match_team_has_player($idmatch_team_has_players)
    {
        return $this->db->get_where('match_team_has_players',array('idmatch_team_has_players'=>$idmatch_team_has_players))->row_array();
    }
        
    /*
     * Get all match_team_has_players
     */
    function get_all_match_team_has_players()
    {
        $this->db->order_by('idmatch_team_has_players', 'desc');
        return $this->db->get('match_team_has_players')->result_array();
    }
        
    /*
     * function to add new match_team_has_player
     */
    function add_match_team_has_player($params)
    {
        $this->db->insert('match_team_has_players',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update match_team_has_player
     */
    function update_match_team_has_player($idmatch_team_has_players,$params)
    {
        $this->db->where('idmatch_team_has_players',$idmatch_team_has_players);
        return $this->db->update('match_team_has_players',$params);
    }
    
    /*
     * function to delete match_team_has_player
     */
    function delete_match_team_has_player($idmatch_team_has_players)
    {
        return $this->db->delete('match_team_has_players',array('idmatch_team_has_players'=>$idmatch_team_has_players));
    }
}
