<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Player_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get player by idplayer
     */

    function get_player($idplayer) {
        return $this->db->get_where('player', array('idplayer' => $idplayer))->row_array();
    }

    /*
     * Get all player
     */

    function get_all_player() {
        $this->db->order_by('idplayer', 'desc');
        return $this->db->get('player')->result_array();
    }

    /*
     * function to add new player
     */

    function add_player($params) {
        $this->db->insert('player', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update player
     */

    function update_player($idplayer, $params) {
        $this->db->where('idplayer', $idplayer);
        return $this->db->update('player', $params);
    }

    /*
     * function to delete player
     */

    function delete_player($idplayer) {
        return $this->db->delete('player', array('idplayer' => $idplayer));
    }

    /*
     * function to filter players
     */

    function get_filtered_players($name, $age, $team) {
        $today = date("Y-m-d");
        $query = "SELECT "
                . "player.idplayer AS idplayer, "
                . "player.current_team AS idteam, "
                . "player.dob AS dob, "
                . "DATEDIFF('" . $today . "', player.dob) / 365.25 as age, "
                . "player.name AS name, "
                . "player.contact AS contact, "
                . "team.short_code AS team "
                . "FROM player "
                . "JOIN team ON player.current_team = team.idteam ";

        if ($name == "" && $team == "" && $age == "") {
            
        } else {
            $query.=" WHERE ";
            if ($name != "") {
                $query.=" player.name LIKE '" . $name . "%' AND ";
            }
            if ($team != "") {
                $query.=" team.short_code='" . $team . "' AND  ";
            }
            if ($age != "") {
                $query.=" DATEDIFF('" . $today . "', player.dob) / 365.25 < " . $age . " AND ";
            }
            $query = substr($query, 0, (strlen($query) - 5));
        }



        $query = $this->db->query($query);

        return $query->result_array();
    }

    function get_players_by_match_team($idMatch, $idTeam) {
        $query = "SELECT "
                . "match_team_has_players.idplayer AS idplayer, "
                . "player.name AS name "
                . "FROM match_team_has_players "
                . "JOIN player ON player.idplayer = match_team_has_players.idplayer "
                . "WHERE idmatch = '" . $idMatch . "' AND idteam = '" . $idTeam . "' ";
        $query = $this->db->query($query);
        return $query->result_array();
    }

    function get_player_by_id($id) {
        $query = "SELECT "
                . "player.current_team AS idteam, "
                . "player.dob AS dob, "
                . "player.name AS name, "
                . "player.contact AS contact, "
                . "player.image AS image, "
                . "team.name AS team "
                . "FROM player "
                . "JOIN team ON team.idteam = player.current_team "
                . "WHERE idplayer = '" . $id . "' ";
        $query = $this->db->query($query);
        $data['basic'] = $query->row_array();
        //
        $query = "SELECT "
                . "match_team_has_players.idmatch AS idmatch, "
                . "matches.from_date AS matchdate, "
                . "matches.team1 AS idteam1, "
                . "matches.team2 AS idteam2, "
                . "team1.short_code AS team1, "
                . "team2.short_code AS team2 "
                . "FROM match_team_has_players "
                . "JOIN matches ON matches.idmatch = match_team_has_players.idmatch "
                . "JOIN team AS team1 ON team1.idteam = matches.team1 "
                . "JOIN team AS team2 ON team2.idteam = matches.team2 "
                . "WHERE idplayer = '" . $id . "'";
        $query = $this->db->query($query);
        $data['match_list'] = $query->result_array();
        //
        $query = "SELECT "
                . "player_has_attribute.idmatch AS idmatch, "
                . "player_has_attribute.idattribute AS idattribute, "
                . "player_has_attribute.level AS level, "
                . "matches.from_date AS matchdate, "
                . "matches.team1 AS team1, "
                . "matches.team2 AS team2, "
                . "attribute.name AS attribute "
                . "FROM player_has_attribute "
                . "JOIN matches ON matches.idmatch = player_has_attribute.idmatch "
                . "JOIN attribute ON attribute.idattribute = player_has_attribute.idattribute "
                . "WHERE idplayer = '" . $id . "'";
        $query = $this->db->query($query);
        $data['attrib_list'] = $query->result_array();

        return $data;
    }

}
