<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Team_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get team by idteam
     */

    function get_team($idteam) {
        return $this->db->get_where('team', array('idteam' => $idteam))->row_array();
    }

    /*
     * Get all team
     */

    function get_all_team() {
        $this->db->order_by('idteam', 'desc');
        return $this->db->get('team')->result_array();
    }

    /*
     * function to add new team
     */

    function add_team($params) {
        $this->db->insert('team', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update team
     */

    function update_team($idteam, $params) {
        $this->db->where('idteam', $idteam);
        return $this->db->update('team', $params);
    }

    /*
     * function to delete team
     */

    function delete_team($idteam) {
        return $this->db->delete('team', array('idteam' => $idteam));
    }

    /*
     * function to filter players
     */

    function get_filtered_teams($name, $code, $address, $contact) {

        $query = "SELECT * FROM team";

        if ($name == "" && $code == "" && $address == "" && $contact == "") {
            
        } else {
            $query.=" WHERE ";
            if ($name != "") {
                $query.=" name LIKE '" . $name . "%' AND ";
            }
            if ($code != "") {
                $query.=" short_code = '" . $code . "' AND  ";
            }
            if ($address != "") {
                $query.=" address LIKE '%" . $address . "%' AND ";
            }
            if ($contact != "") {
                $query.=" contact LIKE '" . $contact . "%' AND ";
            }
            $query = substr($query, 0, (strlen($query) - 5));
        }



        $query = $this->db->query($query);

        return $query->result_array();
    }

}
